### ISSUE TITLE
hello，i meet some errors 

### ISSUE THREAD

**Issue by ChenKevin0123** [lenskit/lenskit-hello#2]
nice to meet u sir. Im a student in China.im learing recommender system now,so I  download lenskit from here."lenskit-hello-master",that's what I downloaded.I read the readme and I followed the steps hoping to see it working.
i setted environments well,then i entered:"C:\LensKit\lenskit-hello> .\gradlew.bat build",build successful.But when i entered"C:\LensKit\lenskit-hello-master> .\build\install\lenskit-hello-master\bin\lenskit-hello-master.bat 72",some errors occured:
C:\Users\chen\Desktop\lenskit-hello-master>.\build\install\lenskit-hello-master\bin\lenskit-hello-master.bat 72
INFO  o.l.c.ConfigurationLoader - loading script from file:/C:/Users/chen/Desktop/lenskit-hello-master/etc/item-item.groovy
INFO  o.l.k.i.m.ItemItemBuildContextProvider - constructing build context
INFO  o.l.k.i.m.ItemItemModelBuilder - building item-item model for 8915 items
java.lang.RuntimeException: Instantiation error on (Provider(org.lenskit.knn.item.model.ItemItemModelBuilder), MEMOIZE)
java.lang.RuntimeException: Instantiation error on (Provider(org.lenskit.knn.item.model.ItemItemModelBuilder), MEMOIZE)
        at org.lenskit.inject.NodeInstantiator.apply(NodeInstantiator.java:57)
        at org.lenskit.inject.NodeInstantiator$DefaultImpl.apply(NodeInstantiator.java:67)
        at org.lenskit.inject.InstantiatingNodeProcessor.processNode(InstantiatingNodeProcessor.java:54)
        at org.lenskit.inject.NodeProcessors.processNodes(NodeProcessors.java:89)
        at org.lenskit.inject.RecommenderInstantiator.replaceShareableNodes(RecommenderInstantiator.java:118)
        at org.lenskit.inject.RecommenderInstantiator.instantiate(RecommenderInstantiator.java:87)
        at org.lenskit.LenskitRecommenderEngineBuilder.build(LenskitRecommenderEngineBuilder.java:122)
        at org.lenskit.LenskitRecommenderEngine.build(LenskitRecommenderEngine.java:257)
        at org.grouplens.lenskit.hello.HelloLenskit.run(HelloLenskit.java:108)
        at org.grouplens.lenskit.hello.HelloLenskit.main(HelloLenskit.java:59)
Caused by: org.grouplens.grapht.ConstructionException: Error invoking provider org.grouplens.grapht.reflect.internal.ClassInstantiator@1a14a4
        at org.grouplens.grapht.Instantiators$ProviderInstantiator.instantiate(Instantiators.java:155)
        at org.grouplens.grapht.Instantiators$MemoizingInstantiator.instantiate(Instantiators.java:184)
        at org.lenskit.inject.NodeInstantiator$DefaultImpl.instantiate(NodeInstantiator.java:76)
        at org.lenskit.inject.NodeInstantiator.apply(NodeInstantiator.java:55)
        ... 9 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at it.unimi.dsi.fastutil.doubles.DoubleArrays.grow(DoubleArrays.java:165)
        at it.unimi.dsi.fastutil.doubles.DoubleArrayList.grow(DoubleArrayList.java:192)
        at it.unimi.dsi.fastutil.doubles.DoubleArrayList.add(DoubleArrayList.java:206)
        at org.grouplens.lenskit.scored.ScoredIdListBuilder.add(ScoredIdListBuilder.java:209)
        at org.grouplens.lenskit.util.UnlimitedScoredItemAccumulator.put(UnlimitedScoredItemAccumulator.java:57)
        at org.lenskit.knn.item.model.ItemItemModelBuilder.get(ItemItemModelBuilder.java:112)
        at org.lenskit.knn.item.model.ItemItemModelBuilder.get(ItemItemModelBuilder.java:50)
        at org.grouplens.grapht.Instantiators$ProviderInstantiator.instantiate(Instantiators.java:153)
        ... 12 more

Can you give me some advices please?Thank you very much.

**Comment by mdekstrand** [comment]
The key error is this:

```
Caused by: java.lang.OutOfMemoryError: Java heap space
at it.unimi.dsi.fastutil.doubles.DoubleArrays.grow(DoubleArrays.java:165)
at it.unimi.dsi.fastutil.doubles.DoubleArrayList.grow(DoubleArrayList.java:192)
at it.unimi.dsi.fastutil.doubles.DoubleArrayList.add(DoubleArrayList.java:206)
at org.grouplens.lenskit.scored.ScoredIdListBuilder.add(ScoredIdListBuilder.java:209)
at org.grouplens.lenskit.util.UnlimitedScoredItemAccumulator.put(UnlimitedScoredItemAccumulator.java:57)
at org.lenskit.knn.item.model.ItemItemModelBuilder.get(ItemItemModelBuilder.java:112)
at org.lenskit.knn.item.model.ItemItemModelBuilder.get(ItemItemModelBuilder.java:50)
at org.grouplens.grapht.Instantiators$ProviderInstantiator.instantiate(Instantiators.java:153)
... 12 more
```

That means that Java does not have enough memory. Try telling Java to use more memory with:

    set JAVA_ARGS=-Xmx2g

(provided you have at least 4, preferably 8, GB of RAM on your system).

**Comment by ChenKevin0123** [comment]
Im very excited to receive your reply!
I run the project in the command line， I just run 
set JAVA_ARGS=-Xmx2g 
in the command line，but it still didn't work. Should I add this sentence to lenskit-hello-master.bat or somewhere else?

**Comment by ChenKevin0123** [comment]
I cannot wait to tell you that I succeed！ I changed the system environment variables，“JAVA_OPTS=-Xms64m -Xmx1g”.
I didn‘t use 2g because when I set 2g，there’s another orror occured————Could not reserve enough space for 2097152KB object heap.
Anyway,it works!Thank you soooooo much and best wishes to you.

**Comment by mdekstrand** [comment]
@ChenKevin0123 Glad to hear it's working.

Are you running a 32-bit Java? That's probably why 2G failed.

And evidently I had the wrong variable name (some things use ARGS, some OPTS, and I was going from memory). I would recommend setting `JAVA_OPTS` each terminal, though, using

    set JAVA_OPTS=-Xmx1g

instead of setting a system environment variable. That way it only affects the program you want to run, rather than possibly affecting other programs on your system.
